name: Trigger auto deployment for app01acae

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/app01acae-AutoDeployTrigger-446a2972-d02a-4f18-b7ab-a4a4663e70d7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerapp0321.azurecr.io
          username: ${{ secrets.APP01ACAE_REGISTRY_USERNAME }}
          password: ${{ secrets.APP01ACAE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerapp0321.azurecr.io/app01acae:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.APP01ACAE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n app01acae -g tamopsaca456-rg --server containerapp0321.azurecr.io --username  ${{ secrets.APP01ACAE_REGISTRY_USERNAME }} --password ${{ secrets.APP01ACAE_REGISTRY_PASSWORD }}
            az containerapp update -n app01acae -g tamopsaca456-rg --image containerapp0321.azurecr.io/app01acae:${{ github.sha }}
